"""生成数据1

Revision ID: 0fb2f0acf46d
Revises: 1ae91bf72e8a
Create Date: 2018-05-28 17:33:27.905481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fb2f0acf46d'
down_revision = '1ae91bf72e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user_news',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    op.add_column('news_info', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('news_info', 'source')
    op.drop_column('news_info', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_info', sa.Column('context', mysql.TEXT(), nullable=True))
    op.add_column('news_info', sa.Column('source', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('news_info', 'content')
    op.drop_table('tb_user_news')
    # ### end Alembic commands ###
